eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    # service-url:
    #   defaultZone: http://discovery-service-0.discovery-service:8761/eureka
    #   # defaultZone: http://localhost:8761/eureka
  instance:
    hostname: host.minikube.internal
    
microservice:
  incident-service:
    endpoints:
      endpoint:
        uri: http://incident-service/incident/test
  authentication-service:
    endpoints:
      endpoint:
        uri: http://authentication-service/auth/test


# eureka:
#   client:
#     register-with-eureka: false
#     fetch-registry: false
#     service-url:
#       defaultZone: http://discovery-service-0.discovery-service:8761/eureka
#       # defaultZone: http://localhost:8761/eureka
#   # instance:
#   #   hostname: host.minikube.internal
