eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
#       defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: discovery-service

microservice:
  incident-service:
    endpoints:
      endpoint:
        uri: http://incident-service-svc/incident/test
  authentication-service:
    endpoints:
      endpoint:
        uri: http://authentication-service-svc/auth/test
