eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service-0.discovery-service:8761/eureka
      defaultZone: http://localhost:8761/eureka

microservice:
  notification-service:
    endpoints:
      endpoint:
        uri: http://notification-service/ws-message
