eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service-0.discovery-service:8761/eureka
  instance:
    hostname: discovery-service-0.discovery-service

microservice:
  notification-service:
    endpoints:
      endpoint:
        uri: http://notification-service:8084/ws-message
